from replit import clear
from colorama import *
from getkey import getkey, keys
pokeDex = False
pokemon = {
"Rattata":{'Name':Fore.RESET + Fore.RESET + "Ratatta [Normal Type]","Desc":"Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area."},
"Bulbasaur": {"Name":Style.BRIGHT + Fore.GREEN + "Bulbasaur [Grass & Poison type]","Desc":"There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger."},
"Squirtle":{"Name":Style.RESET_ALL + Fore.BLUE + "Squirtle [Water type]","Desc":"When it retracts its long neck into its shell, it shoots out water with strong force."},
"Charmander":{"Name":Style.BRIGHT + Fore.RED + "Charmander [Fire type]","Desc":"It has a liking for hot things. When it rains, steam is said to appear from the tip of its tail."},
"Pidgey": {"Name":Style.RESET_ALL + Fore.RESET + "Pidgey [Normal & Flying type]","Desc":"Very submissive. If attacked, it will often kick sand to protect itself instead of fight back."},
"Sandile":{"Name":Style.BRIGHT + Fore.LIGHTBLACK_EX + "Sandile [Ground & Dark type]","Desc":"The desert gets cold at night, so when the sun sets, this Pokémon burrows far into the sand and sleeps until sunrise."},
"Eevee":{"Name":Style.RESET_ALL + Fore.RESET + "Eevee [Normal type]","Desc":"It has the ability to change the composition of its body to fit its needs in its surrounding environment."},
"Sandshrew":{"Name":Style.BRIGHT + Fore.YELLOW + "Sandshrew [Ground Type]","Desc":"Sandshrew hates moisture and lives in holes it digs in dry places. It protects itself by curling into a ball."},
"Skorupi":{"Name":Style.DIM + Fore.MAGENTA + "Skorupi [Bug and Poison Type]","Desc":"Its claws are not only razor-sharp but poisonous, making Skorupi a highly dangerous Pokémon."},
"Machop":{"Name":Style.BRIGHT + Fore.RED + "Machop [Fighting Type]","Desc": "Though as small as a child, it has strength enough to easily throw a well-built adult. Striving to become ever stronger, Machop trains by carrying a Graveler on its shoulders."},
"Abra":{"Name":Style.BRIGHT + Fore.LIGHTMAGENTA_EX + "Abra [Pyschic Type]","Desc":"Spends 18 hours of the day sleeping. Even while asleep, Abra can control its psychic powers—should danger approach, the Pokémon will simply teleport away."},
"Caterpie":{"Name":Style.BRIGHT + Fore.GREEN + "Caterpie [Bug Type]","Desc": "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."},
"Rolycoly":{"Name":Style.DIM + Fore.YELLOW + "Rolycoly [Rock & Type]","Desc":"Most of its body has the same composition as coal. Fittingly, this Pokémon was first discovered in coal mines about 400 years ago."},
"Pikachu":{"Name":Style.BRIGHT + Fore.LIGHTYELLOW_EX + "Pikachu [Electric Type]","Desc":"Possesses cheek sacs in which it stores electricity. This clever forest-dweller roasts tough berries with an electric shock before consuming them."},
"Litwick":{"Name":Style.DIM + Fore.LIGHTMAGENTA_EX + "Litwick [Ghost & Fire Type]","Desc":"The younger the life this Pokémon absorbs, the brighter and eerier the flame on its head burns."},
"Dreepy":{"Name":Style.RESET_ALL + Fore.LIGHTBLUE_EX + "Dreepy [Dragon & Ghost Type]","Desc":"After being reborn as a ghost Pokémon, Dreepy wanders the areas it used to inhabit back when it was alive in prehistoric seas."},
"Aron":{"Name":Style.DIM + Fore.RESET + "Aron [Steel and Rock Type]","Desc":"It usually lives deep in mountains. But when it's hungry, it shows up at the foot of the mountains and eats railroad tracks and cars."},
"Clefairy":{"Name":Style.BRIGHT + Fore.RED + "Clefairy [Fairy Type]","Desc": "It can be found in quiet mountain areas on a full moon's night. Its dancing and its tiny, faintly glowing wings confer upon it a lovely fairylike quality."},
"Spheal":{"Name":Style.BRIGHT + Fore.LIGHTBLUE_EX + "Spheal [Ice & Water Type]","Desc":"This Pokémon's body is covered in blubber and impressively round. It's faster for Spheal to roll around than walk."},
"Noivern":{"Name":Style.DIM + Fore.LIGHTBLUE_EX + "Noivern [Flying & Dragon Type]","Desc":"The Evolved form of Noibat. Although it has a violent disposition, if you give it a nice ripe fruit that it loves, Noivern will suddenly become tame. This is Also "+Fore.RED+"C"+Fore.LIGHTYELLOW_EX+"o"+Style.DIM + Fore.LIGHTGREEN_EX+"lor"+Style.BRIGHT + Fore.CYAN+"ed"+Style.DIM + Fore.BLUE+"Hue"+Style.BRIGHT + Fore.MAGENTA+"'s"+ Fore.RESET + Style.RESET_ALL+" favorite pokemon."},
"Raichu":{"Name":Style.BRIGHT + Fore.LIGHTYELLOW_EX + "Raichu [Electric Type]","Desc":"The Evolved form of Pikachu. It can loose 100,000-volt bursts of electricity, instantly downing foes several times its size."},
"Slowbro":{"Name":Style.BRIGHT + Fore.LIGHTMAGENTA_EX + "Slowbro [Phychic & Water Type]","Desc":"The Evolved form of Slowpoke. Slowpoke became Slowbro when a Shellder bit on to its tail. Sweet flavors seeping from the tail make the Shellder feel as if its life is a dream."},
"Weezing":{"Name":Style.DIM + Fore.MAGENTA + "Weezing [Poison Type]","Desc":"The Evolved form of Koffing. Weezing alternately shrinks and inflates its twin bodies to mix together toxic gases inside. The more the gases are mixed, the more powerful the toxins become. The Pokémon also becomes more putrid."},
"Furret":{"Name":Style.RESET_ALL + Fore.RESET + "Furret [Normal Type]","Desc":"The Evolved form of Sentret. Furret has a very slim build. When under attack, it can slickly squirm through narrow spaces and get away. In spite of its short limbs, this Pokémon is very nimble and fleet."},
"Leafeon":{"Name":Style.BRIGHT + Fore.GREEN + "Leafeon [Grass Type]","Desc":"The Evolved form of Eevee. Cells similar to those of plants have been found in its fur. Its hard tail can fell a large tree with one stroke, and the tail's sharpness exceeds even that of a sword crafted by a master. This is also SuryaRavi1's favorite pokemon."},
"Gyarados":{"Name":Style.RESET_ALL + Fore.RESET + "Gyarados [Flying & Water Type]","Desc":"The Evolved form of Magicarp. Although it obeys its instinctive drive to destroy everything within its reach, it will respond to orders from a Trainer it truly trusts."},
"Jigglypuff":{"Name":Style.BRIGHT + Fore.RED + "Jigglypuff [Fairy & Normal Type]","Desc":"The Evolved form of Igglybuff. Uses its cute round eyes to enrapture its foe. It then sings a pleasing melody that lulls the foe to sleep."},
"Sandslash":{"Name":Style.BRIGHT + Fore.YELLOW + "Sandslash [Ground Type]","Desc":"The Evolved form of Sandshrew. It climbs trees by hooking on with its sharp claws. Sandslash shares the berries it gathers, dropping them down to Sandshrew waiting below the tree."},
"Poliwhirl":{"Name":Style.RESET_ALL + Fore.BLUE + "Polywhirl [Water Type]","Desc":"The Evolved form of Polywag. Staring at the swirl on its belly causes drowsiness. This trait of Poliwhirl's has been used in place of lullabies to get children to go to sleep."},
"Magnemite":{"Name":Style.BRIGHT + Fore.LIGHTYELLOW_EX + "Magnemite [Electric & Steel Type]","Desc":"It subsists on electricity. As Magnemite flies, it emits electromagnetic waves from the units on each side of its body."},
"Farfetch'd":{"Name":Style.RESET_ALL + Fore.RESET + "Farfetch'd [Flying & Normal Type]","Desc":"They use a plant stalk as a weapon, but not all of them use it in the same way. Several distinct styles of stalk fighting have been observed."},
"Serperior":{"Name":Style.BRIGHT + Fore.GREEN + "Serperior [Grass Type]","Desc":"It only gives its all against strong opponents who are not fazed by the glare from Serperior's noble eyes."},
"Charmander":{"Name":Style.RESET_ALL + Fore.RESET + "Charmander [Fire Type]","Desc":"N/A"},
"Polywrath":{"Name":Style.RESET_ALL + Fore.RESET + "Polywrath [Fighting & Water Type]","Desc":"N/A"},
"Ultra-Kyogre":{"Name":Style.RESET_ALL + Fore.RESET + "Ultra-Kyogre [Water Type]","Desc":"N/A"},
"Ninetails":{"Name":Style.RESET_ALL + Fore.RESET + "Ninetails [Fire Type]","Desc":"N/A"},
"Vaporeon":{"Name":Style.RESET_ALL + Fore.RESET + "Vaporeon [Water Type]","Desc":"N/A"},
"Dragonite":{"Name":Style.RESET_ALL + Fore.RESET + "Dragonite [Flying & Dragon Type]","Desc":"N/A"},
"Blastoise":{"Name":Style.RESET_ALL + Fore.RESET + "Blastoise [Water Type]","Desc":"N/A"},
"Porygon2":{"Name":Style.RESET_ALL + Fore.RESET + "Porygon2 [Normal Type]","Desc":"N/A"},
"Gloom":{"Name":Style.RESET_ALL + Fore.RESET + "Gloom [Grass & Poison Type]","Desc":"N/A"},
"Kricketune":{"Name":Style.RESET_ALL + Fore.RESET + "Kricketune [Bug Type]","Desc":"N/A"},
"Arbok":{"Name":Style.RESET_ALL + Fore.RESET + "Arbok [Poison Type]","Desc":"N/A"},
"Dewgong":{"Name":Style.RESET_ALL + Fore.RESET + "Dewgong [Ice & Water Type]","Desc":"N/A"},
"Kadabra":{"Name":Style.RESET_ALL + Fore.RESET + "Kadabra [Psychic Type]","Desc":"N/A"},
"Polarized-Sirfetch'd":{"Name":Style.RESET_ALL + Fore.RESET + "Polarized-Sirfetch'd [Fighting Type]","Desc":"N/A"},
"Golduck":{"Name":Style.RESET_ALL + Fore.RESET + "Golduck [Water Type]","Desc":"N/A"},
"Kingler":{"Name":Style.RESET_ALL + Fore.RESET + "Kingler [Water Type]","Desc":"N/A"},
"Wartortle":{"Name":Style.RESET_ALL + Fore.RESET + "Wartortle [Water Type]","Desc":"N/A"},
"Oddish":{"Name":Style.RESET_ALL + Fore.RESET + "Oddish [Normal & Grass Type]","Desc":"N/A"},
"Voltorb":{"Name":Style.RESET_ALL + Fore.RESET + "Voltorb [Electric Type]","Desc":"N/A"},
"Lickitung":{"Name":Style.RESET_ALL + Fore.RESET + "Lickitung [Normal Type]","Desc":"N/A"},
"Polarized-Meowth":{"Name":Style.RESET_ALL + Fore.RESET + "Polarized-Meowth [Dark Type]","Desc":"N/A"},
"Poliwag":{"Name":Style.RESET_ALL + Fore.RESET + "Poliwag [Water Type]","Desc":"N/A"},
"Bellsprout":{"Name":Style.RESET_ALL + Fore.RESET + "Bellsprout [Grass & Poison Type]","Desc":"N/A"},
"Tentacool":{"Name":Style.RESET_ALL + Fore.RESET + "Tentacool [Water & Poison Type]","Desc":"N/A"},
"Seel":{"Name":Style.RESET_ALL + Fore.RESET + "Seel [Water Type]","Desc":"N/A"},
"Horsea":{"Name":Style.RESET_ALL + Fore.RESET + "Horsea [Water Type]","Desc":"N/A"},
"Rhyhorn":{"Name":Style.RESET_ALL + Fore.RESET + "Rhyhorn [Ground & Rock Type]","Desc":"N/A"},
"Magicarp":{"Name":Style.RESET_ALL + Fore.RESET + "Magicarp [Water Type]","Desc":"N/A"},
"Dratini":{"Name":Style.RESET_ALL + Fore.RESET + "Dratini [Dragon Type]","Desc":"N/A"},
"Gastly":{"Name":Style.RESET_ALL + Fore.RESET + "Gastly [Ghost & Poison Type]","Desc":"N/A"},
"Doduo":{"Name":Style.RESET_ALL + Fore.RESET + "Doduo [Normal & Flying Type]","Desc":"N/A"},
"Psyduck":{"Name":Style.RESET_ALL + Fore.RESET + "Psyduck [Water Type]","Desc":"N/A"},
"Onix":{"Name":Style.RESET_ALL + Fore.RESET + "Onix [Ground & Rock Type]","Desc":"N/A"},
"Grimer":{"Name":Style.RESET_ALL + Fore.RESET + "Grimer [Poison Type]","Desc":"N/A"},
"Shellder":{"Name":Style.RESET_ALL + Fore.RESET + "Shellder [Water Type]","Desc":"N/A"},
"Azurill":{"Name":Style.RESET_ALL + Fore.RESET + "Azurill [Normal & Fairy Type]","Desc":"N/A"},
"Psyduck":{"Name":Style.RESET_ALL + Fore.RESET + "Psyduck [Water Type]","Desc":"N/A"},
"Wooper":{"Name":Style.RESET_ALL + Fore.RESET + "Wooper [Water & Ground Type]","Desc":"N/A"},
"Charizard":{"Name":Style.RESET_ALL + Fore.RESET + "Charizard [Fire & Flying Type]","Desc":"N/A"},
"Flareon":{"Name":Style.RESET_ALL + Fore.RESET + "Flareon [Fire Type]","Desc":"N/A"},
"Vibrava":{"Name":Style.RESET_ALL + Fore.RESET + "Vibrava [Ground & Dragon Type]","Desc":"N/A"},
"Shellder":{"Name":Style.RESET_ALL + Fore.RESET + "Shellder [Water Type]","Desc":"N/A"},
"Azurill":{"Name":Style.RESET_ALL + Fore.RESET + "Azurill [Normal & Fairy Type]","Desc":"N/A"},
"Psyduck":{"Name":Style.RESET_ALL + Fore.RESET + "Psyduck [Water Type]","Desc":"N/A"},
"Wooper":{"Name":Style.RESET_ALL + Fore.RESET + "Wooper [Water & Ground Type]","Desc":"N/A"},
}
order = {
  1:"Bulbasaur",
  2:"Charmander",
  3:"Squirtle",
  4:"Pidgey",
  5:"Eevee",
  6:"Pikachu",
  7:"Skorupi",
  8:"Sandile",
  9:"Sandshrew",
  10:"Machop",
  11:"Abra",
  12:"Caterpie",
  13:"Rolycoly",
  14:"Litwick",
  15:"Dreepy",
  16:"Aron",
  17:"Clefairy",
  18:"Rattata",
  19:"Spheal",
  20:"Noivern",
  21:"Raichu",
  22:"Slowbro",
  23:"Weezing",
  24:"Furret",
  25:"Leafeon",
  26:"Gyarados",
  27:"Jigglypuff",
  28:"Sandslash",
  29:"Poliwhirl",
  30:"Magnemite",
  31:"Farfetch'd",
  32:"Serperior",
  33:"Charmander",
  34:"Polywrath",
  35:"Ultra-Kyogre",
  36:"Ninetails",
  37:"Vaporeon",
  38:"Blastoise",
  39:"Porygon2",
  40:"Gloom",
  41:"Kricketune",
  42:"Arbok",
  43:"Dewgong",
  44:"Vaporeon",
  45:"Kadabra",
  46:"Polarized-Sirfetch'd",
  47:"Golduck",
  48:"Kingler",
  49:"Wartortle",
  50:"Oddish",
  51:"Voltorb",
  52:"Lickitung",
  53:"Polarized-Meowth",
  54:"Vaporeon",
  55:"Kadabra",
  56:"Polarized-Sirfetch'd",
  57:"Poliwag",
  58:"Bellsprout",
  59:"Tentacool",
  60:"Seel",
  61:"Horsea",
  62:"Rhyhorn",
  63:"Magicarp",
  64:"Dratini",
  65:"Gastly",
  66:"Doduo",
  67:"Psyduck",
  68:"Onix",
  69:"Grimer",
  70:"Shellder",
  71:"Azurill",
  72:"Wooper",
  73:"Charizard",
  74:"Flareon",
  75:"Vibrava",
  76:"Mightyena",
  77:"Swellow",
  78:"Lairon",
  79:"Manectric",
  80:"Altaria",
  81:"Ninetails",
  82:"Luxio",
  83:"Gabite",
  84:"Houndoom",
  85:"Polarized-Ninetails",
  86:"Shroomish",
  87:"Vulpix",
  88:"Polarized-Vulpix",
  89:"Geodude",
  90:"Ponyta",
  91:"Cyndaquil",
  92:"Aipom",
  93:"Snubbull",
  94:"Slugma",
  95:"Skarmory",
  96:"Torchic",
  97:"Torkoal",
  98:"Duskull",
  99:"Begon",
  100:"Bronzor",
  101:"Riolu",
  102:"Pidove",
  103:"Milcery",
  104:"Poipole",
}
def select(key):
	clear()
	print(f"{pokemon[key]['Name']}{Fore.RESET + Style.RESET_ALL + Back.RESET}\n{pokemon[key]['Desc']}")
	print("press 'e' to go back")
	print("arrow keys, A and D, or Z and X to move in the pokedex")
def pokeOPEN():
	start = 1
	pokeDex = True
	while pokeDex == True:
		select(order[start])
		key = getkey()
		if key == keys.LEFT or key == keys.A or key ==  keys.Z:
			if start > 1:
		 		start -= 1
		elif key == keys.RIGHT or key == keys.D or key == keys.X:
			if start < len(pokemon):
				start += 1
		elif key == keys.E:
			pokeDex == False
			clear()
			print(Fore.RESET + Style.RESET_ALL + Back.RESET)
			return ''